// Generated by CoffeeScript 1.7.1
(function() {
  var createMiniHarp;

  createMiniHarp = function(root) {
    var app, argv, connect, jadePreprocessor, lessPreprocessor, path, port, serveStatic;
    connect = require("connect");
    app = connect();
    argv = require("minimist")(process.argv.slice(2));
    port = argv.port || 4000;
    serveStatic = require("serve-static");
    jadePreprocessor = require("../lib/processor/jade");
    lessPreprocessor = require("../lib/processor/less");
    path = require("path");
    app.use(function(req, res, next) {
      if (req.url === "current-time") {
        return res.end((new Date()).toISOString() + "\n");
      } else if (req.url === "/") {
        req.url = "/index.html";
        return next();
      } else if (path.extname(req.url) === ".jade" || path.extname(req.url) === ".less") {
        res.statusCode = 404;
        return res.end();
      } else {
        return next();
      }
    }).use(serveStatic(root)).use(jadePreprocessor(root)).use(lessPreprocessor(root)).listen(port);
    console.log("Starting mini-harp on http://localhost:" + port);
    return app;
  };

  module.exports = createMiniHarp;

}).call(this);
