// Generated by CoffeeScript 1.7.1
(function() {
  var makeLess;

  makeLess = function(root) {
    return function(req, res, next) {
      var file, fs, less, path;
      fs = require("fs");
      path = require("path");
      less = require("less");
      if (path.extname(req.url) !== ".css") {
        next();
        return;
      }
      file = path.join(root, req.url);
      if (fs.existsSync(file)) {
        return res.end(file);
      } else {
        file = path.join(root, path.basename(req.url, ".css") + ".less");
        if (fs.existsSync(file)) {
          return fs.readFile(file, {
            encoding: "utf8"
          }, function(err, data) {
            if (err) {
              throw err;
              return next();
            } else {
              return less.render(data, function(e, css) {
                if (e) {
                  throw e;
                  return next();
                } else {
                  res.setHeader("Content-Length", css.length);
                  res.setHeader("Content-Type", "text/css; charset=UTF-8");
                  return res.end(css);
                }
              });
            }
          });
        } else {
          res.statusCode = 404;
          return res.end();
        }
      }
    };
  };

  module.exports = makeLess;

}).call(this);
